import Image from 'next/image'
import Header from '@/components/Header'
import HomePage from '@/components/HomePage'
export const metadata = {
  title: 'Survey',
  description: 'Generated by Survey',
}
export default function Home() {
  return (
    <>
    <Header/>
    <HomePage/>
    </>
  )
}
