import Header from '@/components/Header'
import HomePage from '@/components/HomePage'
import Footer from '@/components/Footer'
export const metadata = {
  title: 'Survey',
  description: 'Generated by Survey',
}
export default function Home() {
  return (
    <>
    <Header/>
    <HomePage/>
    <Footer/>
    </>
  )
}
