import Image from 'next/image'
import Footer from '@/components/Footer'
export const metadata = {
  title: 'Survey',
  description: 'Generated by Survey',
}
export default function Home() {
  return (
    <>
    <Footer/>
    </>
  )
}
